export const healthTips = [
  "Drink enough water throughout the day to stay hydrated.",
  "Walk at least 30 minutes daily for better heart health.",
  "Get 7-9 hours of sleep every night.",
  "Eat more fruits and vegetables with every meal.",
  "Take short breaks if you sit for long periods.",
  "Wash your hands regularly to prevent infections.",
  "Reduce sugary drinks and processed foods.",
  "Stretch your body every morning.",
  "Use sunscreen when spending time outdoors.",
  "Avoid skipping breakfast.",
  "Maintain a healthy body weight.",
  "Exercise at least 150 minutes per week.",
  "Choose whole grains over refined grains.",
  "Practice deep breathing during stressful situations.",
  "Limit screen time before bed.",
  "Keep regular health checkups.",
  "Brush your teeth twice a day.",
  "Floss daily for better oral health.",
  "Eat slowly and mindfully.",
  "Avoid smoking and tobacco products.",
  "Limit alcohol consumption.",
  "Include protein in every meal.",
  "Keep your vaccinations up to date.",
  "Maintain good posture while sitting.",
  "Take the stairs whenever possible.",
  "Read food labels before purchasing products.",
  "Reduce salt intake for healthier blood pressure.",
  "Stay socially connected with friends and family.",
  "Take care of your mental health.",
  "Spend time outdoors regularly.",
  "Keep a consistent sleep schedule.",
  "Avoid overeating late at night.",
  "Listen to your body's warning signs.",
  "Drink water before feeling thirsty.",
  "Keep healthy snacks available.",
  "Practice proper lifting techniques.",
  "Manage stress through exercise or meditation.",
  "Use protective equipment during sports.",
  "Keep your living space clean.",
  "Don't ignore persistent symptoms.",
  "Monitor your blood pressure regularly.",
  "Schedule regular dental visits.",
  "Stay physically active as you age.",
  "Choose water instead of soft drinks.",
  "Eat foods rich in fiber.",
  "Reduce consumption of ultra-processed foods.",
  "Keep emergency medical information accessible.",
  "Take medications exactly as prescribed.",
  "Protect your eyes from excessive screen exposure.",
  "Make health a daily habit, not a temporary goal."
];

export const healthFacts = [
  "The human body contains about 60% water.",
  "Your heart beats around 100,000 times every day.",
  "The brain uses about 20% of your body's energy.",
  "Adults have 206 bones in their body.",
  "Your skin is the body's largest organ.",
  "The average person takes around 20,000 breaths daily.",
  "Blood travels thousands of kilometers through your body each day.",
  "Your lungs contain approximately 300 million air sacs.",
  "Walking can significantly improve cardiovascular health.",
  "Sleep helps your brain process memories.",
  "Laughter can help reduce stress hormones.",
  "Exercise releases feel-good chemicals called endorphins.",
  "Muscles make up around 40% of body weight.",
  "Your body produces vitamin D when exposed to sunlight.",
  "Hydration supports nearly every bodily function.",
  "The liver can regenerate itself after damage.",
  "Regular exercise can improve mental health.",
  "The human eye can distinguish millions of colors.",
  "Your body continuously replaces old cells.",
  "Good sleep strengthens the immune system.",
  "Fruits and vegetables provide essential vitamins and minerals.",
  "The heart pumps about 7,500 liters of blood daily.",
  "Proper hydration supports healthy digestion.",
  "Walking after meals may help regulate blood sugar levels.",
  "The brain remains active even while sleeping.",
  "Stress can affect both physical and mental health.",
  "Strong social connections are linked to longer life expectancy.",
  "Fiber supports digestive health.",
  "The stomach lining renews itself regularly.",
  "Physical activity can reduce the risk of chronic diseases.",
  "Deep breathing may help lower stress levels.",
  "Regular movement improves circulation.",
  "The body contains over 600 muscles.",
  "Sleep deprivation can impair concentration.",
  "Healthy eating supports brain function.",
  "Exercise helps strengthen bones.",
  "Water helps regulate body temperature.",
  "Good posture can reduce strain on muscles and joints.",
  "The kidneys filter waste from your blood continuously.",
  "Your immune system works around the clock.",
  "Heart disease remains one of the leading global health concerns.",
  "Physical activity can improve mood and energy levels.",
  "Healthy habits developed early often last a lifetime.",
  "The tongue contains thousands of taste buds.",
  "The body burns calories even while resting.",
  "Regular health screenings help detect problems early.",
  "Walking is one of the safest forms of exercise.",
  "Maintaining a healthy weight supports joint health.",
  "Quality sleep contributes to overall well-being.",
  "Small healthy choices made consistently can have a big impact over time."
];

export const getAllTipsAndFacts = () => {
  return [...healthTips, ...healthFacts];
};
